name: CI/CD TicketApp

on:
  push:
    branches: [ "master" ]  # ou "main" selon ta branche

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ”„ Cloner le dÃ©pÃ´t
      uses: actions/checkout@v3

    - name: ğŸ³ Installer Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: ğŸ”§ Build backend Docker image
      run: docker build -t ticketapp-backend -f docker/Dockerfile.backend .

    - name: ğŸ”§ Build frontend Docker image
      run: docker build -t ticketapp-frontend -f docker/Dockerfile.frontend .

    - name: âš™ï¸ Lancer lâ€™application avec Docker Compose
      run: docker compose up -d

