name: CI/CD TicketApp

on:
  push:
    branches: [ "main" ]  # ou "master" si câ€™est ton branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ”„ Cloner le repo
      uses: actions/checkout@v3

    - name: ğŸ³ Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: ğŸ”§ Build backend Docker image
      run: docker build -t ticketapp-backend ./backend

    - name: ğŸ”§ Build frontend Docker image
      run: docker build -t ticketapp-frontend ./frontend

    - name: âš™ï¸ Lancer lâ€™application via Docker Compose
      run: docker-compose -f docker-compose.yml up -d
