name: CI/CD TicketApp

on:
  push:
    branches: [ "master" ] 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Cloner le repo
        uses: actions/checkout@v3

      - name: ğŸ³ Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: ğŸ”§ Build backend Docker image
        run: docker build -t ticketapp-backend -f docker/Dockerfile.backend ./backend

      - name: ğŸ”§ Build frontend Docker image
        run: docker build -t ticketapp-frontend -f docker/Dockerfile.frontend ./frontend

      - name: âš™ï¸ Lancer lâ€™application via Docker Compose
        run: docker-compose -f docker-compose.yml up -d
