name: CI/CD TicketApp

on:
  push:
    branches: [ "master" ]  # ou "master" si ton branche principale s'appelle "master"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ”„ Cloner le repo
      uses: actions/checkout@v3

    - name: ğŸ³ Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: ğŸ”§ Build backend Docker image
      run: docker build -t ticketapp-backend -f docker/Dockerfile.backend .

    - name: ğŸ”§ Build frontend Docker image
      run: docker build -t ticketapp-frontend -f docker/Dockerfile.frontend .

    - name: âš™ï¸ Lancer lâ€™application avec Docker Compose
      run: docker-compose up -d
